### ISSUE TITLE
Add NextGen catchment characteristics for GFS downscaling

### ISSUE THREAD

**Issue by jduckerOWP** [mikejohnson51/ngen.hydrofab#4]
The NextGen forcings workstream team has been working on regridding the GFS meteorological forcings data into NextGen catchments. We have been able to successfully regrid the raw GFS data into a NextGen forcings file for the latest hydrofabric data. However, there is a preliminary step that we must take to “downscale” the regridded data into the NextGen catchments based on previous NCAR formulas that were integrated into the WRFHydro Forcings Engine for the National Water Model (NWM). Essentially, the model domain that we must downscale the GFS data for is based on the NextGen catchment characteristics. The following characteristics are needed to downscale GFS data for each NextGen catchment:

1. Mean elevation (meters)
2. Catchment Latitude centroid
3. Catchment Longitude Centroid
4. Mean Catchment Slope (meters or kilometers)
5. Circular mean azimuth
6. Catchment area (meters or kilometers)

**Comment by mikejohnson51** [comment]
Hey @jduckerOWP, here is an initial shot - takes about 80 seconds per VPU using a 1km DEM.

Let me know if this works!

Mike 


```r

gpkg = 'nextgen_01.gpkg'

dem = correct_nwm_spatial(raster('nwmCONUS-v216/geo_em.d01_1km.nc', varname = "HGT_M"))

f = forcing_parameters(gpkg, dem, FALSE)

head(f)


#> # A tibble: 6 × 7
#>   id        areasqkm cetroid_lon centroid_lat elevation slope_m_km aspect
#>   <chr>        <dbl>       <dbl>        <dbl>     <dbl>      <dbl>  <dbl>
#> 1 cat-5660      24.1       -67.8         44.6      29.9       8.76  119. 
#> 2 cat-6158      23.1       -68.5         44.5      59.6      13.6    65.7
#> 3 cat-12402     21.6       -72.1         43.2     501.       20.6   225. 
#> 4 cat-13056     22.6       -72.2         43.2     418.       39.3   251. 
#> 5 cat-13238     22.0       -72.2         43.3     420.       43.4   329. 
#> 6 cat-13563     15.6       -72.7         43.4     575.       67.1    62.6

```

**Comment by jduckerOWP** [comment]
Hi @mikejohnson51 Thank you very much for forwarding this information along! Quick question however, could we just download the geo_em.d01_1km.nc file and extract the forcing parameters data? Our scripts are python based and I believe the example code you illustrated above is R code based correct?

**Comment by mikejohnson51** [comment]
You could for sure but there is some logic in that code to generate the slope and aspect in your desired units along with the area and centroids. Nothing to tricky though... I was just planning on stuffing that table in the hydrofabric attribute table for you on creation because I think some of the info is useful elsewhere (snow modeling?)

**Comment by jduckerOWP** [comment]
I agree. Producing a hydrofabric attribute table is sufficient for our application so we can directly use the generated data in our scripts.  Let me know when you've generated the file and we'll take a look at for our application with GFS downscaling. Thank you again for all your work on this topic!

**Comment by mikejohnson51** [comment]
Sure thing!
